### ISSUE TITLE
recent releases not in helm repo

### ISSUE THREAD

**Issue by oliverpjames** [timescale/timescaledb-kubernetes#155]
the most recent releases haven't been pushed to the helm rep. Is this deliberate/could they be pushed?

**edit**

I'm using helm 2 (not by my choice), is it just that it is not being pushed to the repo for helm 2?

**Comment by mlushpenko** [comment]
Same here, secrets configuration is quite different between the. current documentation and previous release.  Took me some time to figure out what is happening before I realised that latest helm chart hasn't been pushed to the repo.

**Comment by feikesteenbergen** [comment]
This should be fixed with https://github.com/timescale/timescaledb-kubernetes/releases/tag/v0.6.1

**Comment by oliverpjames** [comment]
this still isn't fixed for me

$ helm repo update timescale
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "timescale" chart repository
Update Complete.

$ helm search timescale
NAME                                            CHART VERSION   APP VERSION     DESCRIPTION
timescale-observability/timescaledb-multinode   0.3.0                           TimescaleDB Multinode Deployment.
timescale-observability/timescaledb-single      0.5.5                           TimescaleDB HA Deployment.
timescale/timescaledb-multinode                 0.3.0                           TimescaleDB Multinode Deployment.
timescale/timescaledb-single                    0.5.5                           TimescaleDB HA Deployment.

**Comment by mlushpenko** [comment]
Same here, @feikesteenbergen, issue isn't fixed yet

**Comment by oliverpjames** [comment]
@mlushpenko I've found the issue, I've been using this chart via timescale-observability, which specifies `helm repo add timescale https://charts.timescale.com/`, but in the README of this chart it specifies `helm repo add timescaledb 'https://raw.githubusercontent.com/timescale/timescaledb-kubernetes/master/charts/repo/'`

@feikesteenbergen is there a reason you're not updating `https://charts.timescale.com/`?

**Comment by feikesteenbergen** [comment]
> https://charts.timescale.com/

We probably should add them there, yes.
